version: 2
updates:
  # Keep Go modules up to date
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all Go module updates into a single PR
    groups:
      go-dependencies:
        patterns:
          - "*"
    # Auto-approve minor and patch updates
    open-pull-requests-limit: 5

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all GitHub Actions updates into a single PR
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
