version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: k10s
    main: ./cmd/k10s
    binary: k10s
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X {{ .ModulePath }}/internal/core.Version={{ .Tag }}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [ -trimpath ]

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: shvbsle
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: k10s
    description: "A modern terminal UI for Kubernetes"
    homepage: "https://github.com/shvbsle/k10s"
    license: "Apache-2.0"
    install: |
      bin.install "k10s"
    test: |
      system "#{bin}/k10s", "--version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

nfpms:
  - package_name: k10s
    formats: [deb, rpm]
    homepage: "https://github.com/shvbsle/k10s"
    maintainer: "shvbsle <me@users.noreply.github.com>"
    description: "A modern terminal UI for Kubernetes"
    license: Apache-2.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    contents:
      - src: LICENSE
        dst: /usr/share/doc/k10s/LICENSE
      - src: README.md
        dst: /usr/share/doc/k10s/README.md
    rpm:
      group: Applications/System
      summary: A modern terminal UI for Kubernetes

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: shvbsle
    name: k10s
  prerelease: auto
  draft: false
