version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: k10s
    main: ./cmd/k10s
    binary: k10s
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X {{ .ModulePath }}/internal/core.Version={{ .Tag }}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [ -trimpath ]

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: shvbsle
      name: homebrew-tap
    name: k10s
    description: "A modern terminal UI for Kubernetes"
    homepage: "https://github.com/shvbsle/k10s"
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

scoops:
  - repository:
      owner: shvbsle
      name: scoop-bucket
    name: k10s
    description: "A modern terminal UI for Kubernetes"
    homepage: "https://github.com/shvbsle/k10s"
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

nfpms:
  - package_name: k10s
    formats: [deb, rpm]
    homepage: "https://github.com/shvbsle/k10s"
    maintainer: "shvbsle <me@users.noreply.github.com>"
    description: "A modern terminal UI for Kubernetes"
    license: Apache-2.0

changelog:
  use: git
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
